/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bluoppVR (https://sketchfab.com/bluoppVR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-helmet-7b095c71ce844118bf5fc9af2f3accd0
Title: Space Helmet
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    Material_MR: THREE.MeshStandardMaterial;
  };
};

export function SpaceHelmet(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/space_helmet.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 0]} scale={2.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Material_MR}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../src/assets/space_helmet.glb");
